services:
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Snklp2004$
      - MYSQL_DATABASE=yourcar
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - shared-network
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files:/data_backup/data

  api-prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: nestjs-cars-app
      target: production
      dockerfile: Dockerfile
    command: sh -c './bin/wait-for -t 0 mysqldb:3306 -- npm run start:prod'
    depends_on:
      - mysqldb
    networks:
      - shared-network
    ports:
      - 9000:9000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://api-prod:9000"]
      interval: 5s
      timeout: 3s
      retries: 6

volumes:
  db-config:
  db-data:

networks:
  shared-network:
    driver: bridge
